### ISSUE TITLE
[Bug]: GCP - Compute service with no findings

### ISSUE THREAD

**Issue by remote-tty1** [toniblyx/prowler#3077]
### Steps to Reproduce

 1. `./prowler.py gcp -s compute --log-level ERROR --credentials-file filename.json`
 2. GCP
 3. single project within an organization
 4. "There are no findings in Project"

### Expected behavior

At least one failure for the instance with ssh port exposed on the internet

### Actual Result with Screenshots or Logs
```
Executing 17 checks, please wait...
2023-11-28 16:40:47,065 [File: service.py:82] 	[Module: service]	 ERROR: UnknownApiNameOrVersion[80]: name: Compute  version: v1
2023-11-28 16:40:48,607 [File: compute_service.py:245] 	[Module: compute_service]	 ERROR: AttributeError[228]: 'NoneType' object has no attribute 'urlMaps'
2023-11-28 16:40:48,607 [File: compute_service.py:43] 	[Module: compute_service]	 ERROR: AttributeError[32]: 'NoneType' object has no attribute 'regions'
2023-11-28 16:40:48,607 [File: compute_service.py:77] 	[Module: compute_service]	 ERROR: AttributeError[69]: 'NoneType' object has no attribute 'projects'
2023-11-28 16:40:48,607 [File: compute_service.py:61] 	[Module: compute_service]	 ERROR: AttributeError[50]: 'NoneType' object has no attribute 'zones'
2023-11-28 16:40:48,607 [File: compute_service.py:163] 	[Module: compute_service]	 ERROR: AttributeError[139]: 'NoneType' object has no attribute 'networks'
2023-11-28 16:40:48,607 [File: compute_service.py:221] 	[Module: compute_service]	 ERROR: AttributeError[200]: 'NoneType' object has no attribute 'firewalls'
2023-11-28 16:40:48,637 [File: service.py:82] 	[Module: service]	 ERROR: UnknownApiNameOrVersion[80]: name: DNS  version: v1
2023-11-28 16:40:49,987 [File: dns_service.py:39] 	[Module: dns_service]	 ERROR: AttributeError[19]: 'NoneType' object has no attribute 'managedZones'
2023-11-28 16:40:49,987 [File: dns_service.py:68] 	[Module: dns_service]	 ERROR: AttributeError[46]: 'NoneType' object has no attribute 'policies'
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 17/17 [100%] in 3.0s 
 There are no findings in Project ID/s
```

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Workstation

### OS used

Ubuntu 22.04.3 LTS

### Prowler version

Prowler 3.11.3

### Pip version

pip 23.3.1

### Context

For the authentication, I'm using a service principal with the viewer role associated
For your information, Cloud SQL controls are working properly and producing relevant results using the same credentials

**Comment by n4ch04** [comment]
Hi @remote-tty1, we are inspecting this. It seems that there are problems generating the client for both services ...
Can you verify that those two apis are enabled for the project?

**Comment by remote-tty1** [comment]
Hi, thank you for the reply 
I can confirm that both services have their api enabled (and are shown in the API & Services summary screen)

**Comment by n4ch04** [comment]
From https://github.com/googleapis/google-api-python-client/blob/main/docs/dyn/index.md `Compute` has three API versions, and `DNS` has two.

Can you verify which versions are available for those services?
While we debug this I'm gonna also add some error handling to that piece of code to not generate such kind of messages

**Comment by remote-tty1** [comment]
Sorry for the delay
I got this from the API & Services > Methods area

compute: v1 and beta methods
> compute.beta.AcceleratorTypesService.List
compute.beta.DiskTypesService.List
compute.beta.FirewallsService.Get
compute.beta.FirewallsService.List
compute.beta.InstancesService.AggregatedList
compute.beta.InstancesService.ListReferrers
compute.beta.MachineTypesService.List
compute.beta.NetworkFirewallPoliciesService.List
compute.beta.NetworksService.GetEffectiveFirewalls
compute.beta.NetworksService.List
compute.beta.ProjectsService.Get
compute.beta.ProjectsService.GetXpnResources
compute.beta.RegionDiskTypesService.List
compute.beta.RegionNetworkFirewallPoliciesService.List
compute.beta.RegionsService.List
compute.beta.SubnetworksService.AggregatedList
compute.beta.ZonesService.List
compute.v1.DisksService.Get
compute.v1.FirewallsService.Get
compute.v1.FirewallsService.Insert
compute.v1.FirewallsService.List
compute.v1.GlobalOperationsService.Get
compute.v1.InstancesService.AggregatedList
compute.v1.InstancesService.Get
compute.v1.InstancesService.Insert
compute.v1.InstancesService.List
compute.v1.InstancesService.SetMetadata
compute.v1.InstancesService.Start
compute.v1.InstancesService.Stop
compute.v1.NetworksService.Get
compute.v1.NetworksService.Insert
compute.v1.NetworksService.List
compute.v1.ProjectsService.Get
compute.v1.ProjectsService.GetXpnHost
compute.v1.RegionOperationsService.Get
compute.v1.RegionsService.List
compute.v1.SubnetworksService.Get
compute.v1.SubnetworksService.Insert
compute.v1.SubnetworksService.List
compute.v1.UrlMapsService.List
compute.v1.ZoneOperationsService.Get
compute.v1.ZoneOperationsService.Wait
compute.v1.ZonesService.Get
compute.v1.ZonesService.List

dns: v1 and dev methods

> cloud.dns.api.dev.ManagedZonesService.List
cloud.dns.api.dev.PoliciesService.List
cloud.dns.api.v1.ManagedZonesService.List
cloud.dns.api.v1.PoliciesService.List

The project I'm using was created recently and few APIs have been enabled so far and even if you try to enable all the APIs in the Compute category, the result doesn't change

**Comment by n4ch04** [comment]
@remote-tty1  I am not able to reproduce the issue, but I added a workaround with another APIs trying to solve it.
The changes are in branch `bypass-compute-service`, could you switch to that branch and try it?
The steps would be:
- clone the repo -> go to the prowler directory
- `git checkout bypass-compute-service`
- `gcloud auth application-default set-quota-project <your-project-id>`
- `./prowler.py gcp -s compute --log-level ERROR`

Can you give it a try and let us know?
Also we encourage you to join our slack https://join.slack.com/t/prowler-workspace/shared_invite/zt-289luudtv-msHqryT3a1klQ1DrFYTpvA

**Comment by remote-tty1** [comment]
I followed a slightly different procedure because I use a credentials file and not a gcloud cli

Steps followed:
- git pull
- git checkout bypass-compute-service
- poetry install
  - output:
      • Updating cachetools (4.2.4 -> 5.3.0)
  • Updating cryptography (41.0.4 -> 41.0.6)
  • Updating protobuf (3.20.3 -> 4.23.0)
  • Updating google-auth (1.35.0 -> 2.17.3)
  • Installing jsonpickle (3.0.2)
  • Installing jsonpointer (2.4)
  • Installing mpmath (1.3.0)
  • Installing aws-sam-translator (1.80.0)
  • Installing ecdsa (0.18.0)
  • Installing junit-xml (1.9)
  • Updating google-api-core (1.34.0 -> 2.11.0)
  • Installing jschema-to-python (1.2.3)
  • Installing jsonpatch (1.33)
  • Updating grpcio-status (1.48.2 -> 1.59.3)
  • Installing networkx (3.2.1)
  • Installing regex (2023.8.8)
  • Installing sarif-om (1.0.4)
  • Installing sympy (1.12)
  • Installing wrapt (1.16.0)
  • Installing aws-xray-sdk (2.12.1)
  • Installing cfn-lint (0.83.3)
  • Installing graphql-core (3.2.3)
  • Installing jsondiff (2.0.0)
  • Installing multipart (0.2.4)
  • Installing py-partiql-parser (0.4.2)
  • Installing python-jose (3.3.0)
  • Installing sshpubkeys (3.3.1)
  • Updating uritemplate (3.0.1 -> 4.1.1)
  • Downgrading google-api-python-client (2.109.0 -> 2.108.0)
  • Updating moto (4.2.7 -> 4.2.10)
  • Updating pytest-xdist (3.3.1 -> 3.5.0)
  • Downgrading slack-sdk (3.26.1 -> 3.26.0)

- ./prowler.py gcp -s compute --log-level ERROR --credentials-file credentials.json

Regarding the API quotas:
on my project, for every enabled service API, I have less than 40% utilization 

...and I have good news:

I got this errors

> Executing 17 checks, please wait...
2023-12-05 09:19:35,705 [File: service.py:82] 	[Module: service]	 ERROR: UnknownApiNameOrVersion[80]: name: Compute  version: v1
2023-12-05 09:19:48,886 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-central2-c -- ValidationError[119]: 2 validation errors for Instance
metadata
  value is not a valid dict (type=type_error.dict)
service_accounts
  value is not a valid list (type=type_error.list)
2023-12-05 09:19:51,283 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-central1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/me-central1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,316 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west4-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west4-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,339 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-west1-a -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:51,555 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-west1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/me-west1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,570 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: southamerica-east1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/southamerica-east1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,610 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-southeast1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-southeast1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,625 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east5-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east5-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,675 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west12-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west12-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,690 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: southamerica-west1-b -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:51,752 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-north1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-north1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,771 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west6-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west6-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,832 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,842 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,866 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,952 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,966 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-central1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-central1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,971 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-central2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-central2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,976 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:51,998 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east5-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east5-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,000 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-north1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-north1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,006 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-west1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/me-west1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,009 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-central1-c -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:52,025 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-south1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-south1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,033 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,037 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west3-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west3-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,119 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west3-b -- ConnectionError[111]: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-12-05 09:19:52,137 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,138 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west4-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west4-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,180 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast3-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast3-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,204 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,221 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-central1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/me-central1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,235 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast3-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast3-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,239 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,259 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: australia-southeast2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/australia-southeast2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,260 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-southeast2-c -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:52,266 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: australia-southeast1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/australia-southeast1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,271 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,279 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west10-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west10-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,280 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,318 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west6-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west6-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,320 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-southwest1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-southwest1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,327 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east5-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east5-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,333 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-south1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-south1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,346 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: southamerica-east1-c -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:52,375 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,388 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west4-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west4-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,392 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east4-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east4-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,399 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: southamerica-west1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/southamerica-west1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,411 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west9-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west9-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,440 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,462 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west10-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west10-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,465 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,474 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-central1-f -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-central1-f/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,482 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west6-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west6-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,489 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: australia-southeast1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/australia-southeast1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,491 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-north1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-north1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,501 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west3-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west3-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,510 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,516 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: northamerica-northeast2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/northamerica-northeast2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,524 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: australia-southeast2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/australia-southeast2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,531 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west8-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west8-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,540 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: northamerica-northeast2-b -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:52,543 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west8-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west8-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,548 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west3-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west3-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,550 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west10-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west10-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,564 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,576 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west12-c -- ConnectionError[111]: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-12-05 09:19:52,577 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,580 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-south1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-south1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,584 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: northamerica-northeast2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/northamerica-northeast2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,595 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-south2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-south2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,600 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,603 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,612 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-east1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-east1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,613 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,637 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west3-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west3-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,638 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,652 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west12-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west12-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,666 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast3-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast3-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,673 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west2-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west2-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,678 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-south2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-south2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,680 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east4-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east4-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,721 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: southamerica-east1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/southamerica-east1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,722 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east4-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east4-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,725 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: asia-northeast1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/asia-northeast1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,726 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-west2-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-west2-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,729 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: me-central2-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/me-central2-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,730 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-south1-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-south1-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,732 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-south1-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-south1-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,735 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: us-east1-d -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/us-east1-d/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,737 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west9-c -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west9-c/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,738 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west4-b -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west4-b/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,740 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: northamerica-northeast1-a -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/northamerica-northeast1-a/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:19:52,740 [File: compute_service.py:192] 	[Module: compute_service]	 ERROR: europe-west1-d -- SSLError[111]: HTTPSConnectionPool(host='compute.googleapis.com', port=443): Max retries exceeded with url: /compute/v1/projects/xxxxxxx-xxxxxx/zones/europe-west1-d/instances (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))
2023-12-05 09:20:01,217 [File: service.py:82] 	[Module: service]	 ERROR: UnknownApiNameOrVersion[80]: name: DNS  version: v1
2023-12-05 09:20:02,507 [File: dns_service.py:39] 	[Module: dns_service]	 ERROR: AttributeError[19]: 'NoneType' object has no attribute 'managedZones'
2023-12-05 09:20:02,507 [File: dns_service.py:68] 	[Module: dns_service]	 ERROR: AttributeError[46]: 'NoneType' object has no attribute 'policies'
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 17/17 [100%] in 27.7s

...but...It works now!

> │ Provider   │ Service        │ Status    │   Critical │   High │   Medium │   Low │
   │ gcp           │ networking │ FAIL (3)   |            3 │         0 │              0 │        0 │
   │ gcp           │ compute    │ FAIL (44) │           0 │         1 │            42 │        1 │

after that, I was puzzled by the result got with poetry and I tried to check if the result was due to unmatched requirements...so I switched back to the master branch and tried again with poetry install and the same prowler command but in that test I got no output so it currently work only on your branch

Let me know if you need other info or tests 

Thanks in advance

**Comment by MrCloudSec** [comment]
Hi @remote-tty1 , this issue was fixed with https://github.com/prowler-cloud/prowler/pull/3202. Can you try it again with the latest version? Thanks!

**Comment by remote-tty1** [comment]
Sorry for the delay
I tried the latest version (commit: 78505cb0a8e240cdceebd436335f68f941997853) and it works correctly without showing the errors indicated in the previous comment!

Thank you!

**Comment by sadjaneximietas** [comment]
I have the same problem but I still can't understand how it worked for you.


Edit: It worked somehow.

**Comment by jfagoagas** [comment]
Hi @sadjaneximietas what version of Prowler are you using?

**Comment by sadjaneximietas** [comment]
> Hi @sadjaneximietas what version of Prowler are you using?

I faced the problem in version 3.12.1, then I followed OP's steps. Then I changed the version to 3.11.3, it showed some problems and after some fixes it worked.
