### ISSUE TITLE
Kubernetes Job Fails to Start - prowler Executable Not Found in Latest Version

### ISSUE THREAD

**Issue by petrobubka** [toniblyx/prowler#7530]
### Steps to Reproduce

Hi Prowler Team,

After updating to the latest version of Prowler, I'm encountering an error when trying to run it as a Kubernetes job. The container fails.
This seems like a packaging issue in the latest image - possibly the binary isn't in the expected path or not marked as executable. Rolling back to an earlier version resolves the issue.

Would be great to have a fix or a workaround confirmed. Thanks in advance for the help!

### Expected behavior

The container should start and run prowler as the entrypoint.

### Actual Result with Screenshots or Logs

`
Warning  Failed     62s   kubelet  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "prowler": executable file not found in $PATH: unknown`

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

k8s

### OS used

-

### Prowler version

5.5.0

### Pip version

-

**Comment by danibarranqueroo** [comment]
Hi @petrobubka!

This seems to be related to the same issue we've been seeing since the release of v5.5.0. We've already fixed it and are currently preparing a new release. Stay tuned and once it's out, please try again and let us know if the error is resolved.

This is the other issue linked with the PR of the fix: https://github.com/prowler-cloud/prowler/issues/7509

Thanks for reaching out!

**Comment by danibarranqueroo** [comment]
Hi again @petrobubka! The release is now done, please check out that the error disappeared 🙏

**Comment by petrobubka** [comment]
Looks like the problem still persists

 Normal   Pulled     37s   kubelet            Successfully pulled image "toniblyx/prowler:5.5.1" in 673ms (673ms including waiting). Image size: 775354589 bytes.
  Normal   Created    37s   kubelet            Created container: prowler
  Warning  Failed     37s   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "prowler": executable file not found in $PATH: unknown

**Comment by CbtGit73** [comment]
I'm having the exact same problem. 
Warning  Failed     72s   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "prowler": executable file not found in $PATH: unknown

**Comment by danibarranqueroo** [comment]
Hi @petrobubka @CbtGit73,

Thanks for the follow-up and for confirming that the issue still persists in version 5.5.1.

We're currently investigating this behavior, as it appears to be a strange and unexpected issue related to how the container is built or initialized. 

We'll update this thread as soon as we identify the root cause or have a workaround available. Thanks for your patience and for helping us track it down!

**Comment by jfagoagas** [comment]
Hello @petrobubka @CbtGit73 I apologise for the issue you're facing. I'd like to know how are you running `toniblyx/prowler` because in https://github.com/prowler-cloud/prowler/pull/7112 we updated to Poetry v2 which forced us to change the container's `ENTRYPOINT`:
- Previous: `ENTRYPOINT ["prowler"]`
- Actual: `ENTRYPOINT ["poetry", "run", "prowler"]`

This should not introduce a breaking change if you are not overriding the container's `ENTRYPOINT`:
```shell
$ docker run toniblyx/prowler:5.5.1                                                    
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v5.5.1
|_| the handy multi-cloud security tool

Date: 2025-04-22 12:02:23
```

Please let us know more about how you run the image to see if there is something we can fix in our end.

Thanks for using Prowler 🚀

**Comment by petrobubka** [comment]
Hey @jfagoagas

I am using k8s in-cluster execution with a job you have under this path in a repo
_prowler/kubernetes/job.yaml_

Here is the part from it :
      - name: prowler
        image: toniblyx/prowler:stable
        command: ["prowler"]
        args: ["kubernetes", "-z"]

**Comment by jfagoagas** [comment]
@petrobubka I know where the issue is 👏 

Could you please remove the line with `command: ["prowler"]`? Because the `command` replaces the container's `ENTRYPOINT`.

**Comment by petrobubka** [comment]
Yeah, it was really the issue
I just tried removing `command: ["prowler"]` , it works as expected now

Thank you!

**Comment by jfagoagas** [comment]
Thank you for your prompt response, and I apologize for the inconvenience. I’m glad to see it’s working perfectly now.

Thanks for using Prowler! 🚀

**Comment by blaargh** [comment]
just want to report, this is still really unfortunate that it was not documented correctly. I am using a custom entrypoint to pre- and post-process stuff before and after running prowler. So I had to check the official Dockerfile and find out it is now running via poetry. So in my custom entrypoint I replaced the direct prowler binary call with: `poetry run prowler`, same as in the Dockerfile. 

It works like this now, but it's really annoying to break stuff like that without any information. Not the first time this happened either, like the change from alpine based image to debian.
